[program:ghostship_xvfb]
command=/usr/bin/Xvfb :99 -screen 0 1920x1080x24 -nolisten tcp
priority=1
autorestart=true
startsecs=1
startretries=3
stopasgroup=true
killasgroup=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
